g++ -c model/user.cpp
g++ -c model/expense.cpp
g++ -c model/equalExpen.cpp
g++ -c model/exactExpense.cpp
g++ -c repository/userRepository.cpp
g++ -c repository/expenseRepository.cpp
g++ -c service/expenseService.cpp
g++ -c service/expenseManager.cpp
g++ -c main.cpp
g++ -o main main.o user.o expense.o equalExpen.o exactExpense.o expenseService.o expenseManager.o userRepository.o expenseRepository.o
./main



g++ -c main.cpp 
g++ -o ok main.o
.\ok  